-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local primary = "rgb(ebdbb2)"
local surface = "rgb(282828)"
local secondary = "rgb(8ec07c)"
local error = "rgb(fb4934)"
local tertiary = "rgb(83a598)"
local surface_lowest = "rgb(2c2b2a)"

hl.config({
    general = {
        col = {
            active_border = "rgb(ebdbb2)",
            inactive_border = "rgb(282828)",
        }
    },
})

hl.config({
    group = {
        col = {
            border_active = "rgb(8ec07c)",
            border_inactive = "rgb(282828)",
            border_locked_active = "rgb(fb4934)",
            border_locked_inactive = "rgb(282828)",
        },
        groupbar = {
            col = {
                active = "rgb(8ec07c)",
                inactive = "rgb(282828)",
                locked_active = "rgb(fb4934)",
                locked_inactive = "rgb(282828)",
            }
        },
    },
})
