#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

# Rosé pine 
bspc config focused_border_color "#9ccfd8"

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhdk &
polybar -r &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &

firefox &
kitty &
discord &
cider &

bspc rule -a discord desktop=^9 follow=off -o
bspc rule -a Cider desktop=^10 follow=off -o
bspc rule -a firefox desktop=^2 follow=off -o
bspc rule -a kitty desktop=^1 follow=off -o
